Hide Available Data page
ScilifelabDataCentre/pathogens-portal pull request #1166
Opened 2024-08-08 14:08 UTC by misterabdullahAziz

2024-08-09 06:35 UTC, LianeHughes requested changes
'see all datasets' link on front page is broken after this change. This needs fixing. Otherwise, looks good!

2024-08-12 08:29 UTC, senthil10 approved these changes

2024-08-12 09:59 UTC, senthil10 commented
Looks good to me, can be merge when @LianeHughes is happy and approved :)

2024-08-12 11:08 UTC, LianeHughes approved these changes

2024-08-12 11:08 UTC, LianeHughes commented
Changes now completed as requested.

2024-08-12 11:08 UTC, merged