Freya 857/abdullah
ScilifelabDataCentre/pathogens-portal pull request #1167
Opened 2024-08-08 14:29 UTC by misterabdullahAziz

updated editorial members as well as added a section for alumni.

2024-08-09 06:23 UTC, LianeHughes approved these changes
Looks really good! Made minor edits to the picture so that it was the same size as the others

2024-08-09 06:54 UTC, senthil10 requested changes
Nice work Abdullah, just one comment. It is better to tweak the current shortcode a little, so we can pass the data file name as argument. That way we don't need another shortcode for this 👍

2024-08-09 07:25 UTC, misterabdullahAziz commented
> Nice work Abdullah, just one comment. It is better to tweak the current shortcode a little, so we can pass the data file name as argument. That way we don't need another shortcode for this 👍

I was thinking the same, but was not sure and tried to keep it clean. 
Will fix this.

2024-08-13 06:15 UTC, senthil10 approved these changes

2024-08-13 14:49 UTC, merged