News on SARS-CoV2 variant Competition Dashboard
ScilifelabDataCentre/pathogens-portal pull request #1184
Opened 2024-09-04 10:22 UTC by HamsaiyniVenkatesh

Updated the content on md file, includes images for thumbnail and content graph.

2024-09-04 10:39 UTC, LianeHughes commented on data/available_datasets.json
>    "last_updated": "2024-06-10",
```suggestion
  "last_updated": "2024-09-04",
```

2024-09-04 12:46 UTC, LianeHughes requested changes
On the available data file, please ensure that the data is from the publication itself. Correction is needed for the spelling of 'protein' (in data type and database name), and the tag for protein data should align to what is used in the rest of the file (I think 'Protein data', please check). Description text should also use British English spelling.

2024-09-04 12:47 UTC, LianeHughes commented
and publications file should be uploaded

2024-09-04 14:01 UTC, HamsaiyniVenkatesh commented
The publication file is added in a right branch with details for the task number ( as added the data here in this branch was a mistake) , the publication file is in the Hamsa/Freya- 833,834

2024-09-05 05:09 UTC, LianeHughes approved these changes
corrections added

2024-09-05 05:09 UTC, merged